language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

env:
    - GIMME_OS=linux GIMME_ARCH=amd64
    - GIMME_OS=darwin GIMME_ARCH=amd64
    - GIMME_OS=windows GIMME_ARCH=amd64
    - GIMME_OS=linux GIMME_ARCH=arm GIMME_ARM=6


install:
    - go get -d -v ./rename
    - go get -d -v ./mame-history
    - go get -d -v .

script:
    - go build -o rename-bin -v ./rename
    - go build -o mame-history-bin -v ./mame-history
    - go build -v .
    - ./scripts/run-tests.sh
