language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

env:
    - GIMME_OS=linux GIMME_ARCH=amd64
    - GIMME_OS=linux GIMME_ARCH=i386
    - GIMME_OS=darwin GIMME_ARCH=amd64
    - GIMME_OS=darwin GIMME_ARCH=i386
    - GIMME_OS=windows GIMME_ARCH=amd64
    - GIMME_OS=windows GIMME_ARCH=i386
    - GIMME_OS=linux GIMME_ARCH=arm GIMME_ARM=6
    - GIMME_OS=linux GIMME_ARCH=arm GIMME_ARM=7


install:
    - go get -d -v ./...

script:
    - go build -v ./...
    - go test ./...
